language: go

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"
  - "1.17.x"
  - "1.18.x"
  - "master"

os:
  - linux

go_import_path: github.com/axiaoxin-com/logging

env:
  - GO111MODULE=on

install:
  - go mod tidy

script:
  - go test -race -v .
